### ISSUE TITLE
e2etest TestLocalTransfer failure 

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-core#2484]
On current master commit b42f7a1e57b994e0f27a8d3f6e0cf6a98ba14f48, e2etest/local_transfer_test.go TestLocalTransfer fails. 

```
    local_transfer_test.go:322:
        	Error Trace:	local_transfer_test.go:322
        	            				local_transfer_test.go:439
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestLocalTransfer
2020-10-25T00:22:32.982+0900	ERROR	itx/server.go:212	Error when serving metrics data.	{"error": "context canceled"}
github.com/iotexproject/iotex-core/server/itx.StartServer.func3
	/Users/seoyoungko/go/src/github.com/iotexproject/iotex-core/server/itx/server.go:212
github.com/iotexproject/iotex-core/server/itx.StartServer
	/Users/seoyoungko/go/src/github.com/iotexproject/iotex-core/server/itx/server.go:231
2020-10-25T00:22:32.982+0900	ERROR	itx/server.go:224	Error when serving performance profiling data.	{"error": "http: Server closed"}
github.com/iotexproject/iotex-core/server/itx.StartServer.func4
	/Users/seoyoungko/go/src/github.com/iotexproject/iotex-core/server/itx/server.go:224
2020-10-25T00:22:32.982+0900	ERROR	go-p2p@v0.2.12/p2p.go:449	Error when subscribing a broadcast message.	{"error": "subscription cancelled by calling sub.Cancel()"}
github.com/iotexproject/go-p2p.(*Host).AddBroadcastPubSub.func1
	/Users/seoyoungko/go/pkg/mod/github.com/iotexproject/go-p2p@v0.2.12/p2p.go:449
--- FAIL: TestLocalTransfer (25.19s)
```

**Comment by dustinxie** [comment]
this used to be an unexposed bug, and has been fixed in https://github.com/iotexproject/iotex-core/commit/ad002d46046497b68d7bcff23b908eb0033c12a2

on latest master, test can pass either by `make test` or `go test -race -run TestLocalTransfer` on my local macOS

@koseoyoung  could you provide details how to repro/expose this failure?

**Comment by koseoyoung** [comment]
Hmm on my local macOS, I just tried both cmds, but it still fails. Last time, I tried ```go test -v -run TestLocalTransfer ``` and just ```make```. 
my go version is 1.15.2.

**Comment by dustinxie** [comment]
@koseoyoung  pls reopen if you find more or know the root-cause
